In [4]:
data_list=[1,2,3]

In [5]:
import numpy as np

In [6]:
arr = np.array(data_list)
arr

array([1, 2, 3])

In [7]:
data_list2= [[10,20,30],[40,50,60],[70,80,90]]

In [9]:
arr2 = np.array(data_list2)
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr3=np.array([1,2,3,4,5])

In [11]:
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr3[0]

1

In [13]:
arr3[4]

5

In [14]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr[2,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
arr2[2,2]

90

In [17]:
arr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [18]:
arr2[0,1

SyntaxError: unexpected EOF while parsing (255015293.py, line 1)

In [19]:
arr2[0,1]

20

In [20]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(0,10)

5

In [33]:
np.random.randint(15)

7

In [34]:
np.random.randint(1,10,5)

array([9, 1, 4, 5, 7])

In [35]:
np.random.rand(5)

array([0.67588559, 0.85824162, 0.18994319, 0.17647089, 0.66305264])

In [36]:
np.random.randn(5)

array([ 1.03262488,  0.65376639,  0.06317479, -0.59411661,  0.61056254])

In [37]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [40]:
newArray=np.random.randint(1,100,10)

In [41]:
newArray

array([41, 54, 81, 40, 60, 38, 12,  3, 72, 72])

In [42]:
newArray.max()

81

In [43]:
newArray.min()

3

In [44]:
newArray.sum()

473

In [45]:
newArray.mean()

47.3

In [46]:
newArray.argmax()

2

In [47]:
newArray.argmin()

7

In [48]:
detArray=np.random.randint(1,100,25)

In [49]:
detArray

array([35, 51, 67, 27, 59, 48, 40, 23, 23, 17, 65, 13, 87,  8, 20, 56, 56,
        5, 19,  7, 94, 32, 39,  3, 59])

In [50]:
detArray = detArray.reshape(5,5)

In [51]:
detArray

array([[35, 51, 67, 27, 59],
       [48, 40, 23, 23, 17],
       [65, 13, 87,  8, 20],
       [56, 56,  5, 19,  7],
       [94, 32, 39,  3, 59]])

In [52]:
np.linalg.det(detArray)

166147859.99999976

In [53]:
round(np.linalg.det(detArray))

166147860

In [54]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[1]

2

In [56]:
arr[3]

4

In [57]:
arr[1:5]

array([2, 3, 4, 5])

In [58]:
arr[0:4]

array([1, 2, 3, 4])

In [59]:
arr[:4]

array([1, 2, 3, 4])

In [60]:
arr[::2]

array([1, 3, 5, 7, 9])

In [61]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[:3] 

array([1, 2, 3])

In [63]:
arr[:3]=25

In [64]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [65]:
arr=np.arange(1,10)

In [66]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr2=arr

In [68]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr2[:3]=100

In [70]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [71]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [72]:
arr = np.arange(1,10)

In [73]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr2= arr.copy()

In [75]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [77]:
arr2[:3]=100

In [78]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [79]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
newArray = np.arange(1,21)

In [81]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [83]:
newArray=newArray.reshape(5,4)

In [84]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [85]:
newArray[0,0]

1

In [86]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [87]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [89]:
arr = np.arange(1,11)

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [92]:
booleanArray = arr > 3

In [93]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[arr >5]

array([ 6,  7,  8,  9, 10])

In [106]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [107]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [108]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [109]:
arr1*arr2

array([ 20,  60, 120, 200, 300, 420])

In [110]:
arr1

array([10, 20, 30, 40, 50, 60])

In [111]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [112]:
arr2

array([2, 3, 4, 5, 6, 7])

In [113]:
arr2-2

array([0, 1, 2, 3, 4, 5])

In [114]:
arr1

array([10, 20, 30, 40, 50, 60])

In [115]:
arr1 /3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [116]:
round(arr1/3)

TypeError: type numpy.ndarray doesn't define __round__ method

In [117]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [118]:
np.ones(1)

array([1.])

In [119]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [121]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [122]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.ones(5) =10

SyntaxError: cannot assign to function call (906646203.py, line 1)

In [124]:
arr[:5]

array([1, 2, 3, 4, 5])

In [133]:
arr[:5]=10

In [134]:
arrdeneme=np.array([1,2,3,4,5])

In [135]:
arrdeneme

array([1, 2, 3, 4, 5])

In [136]:
arrdeneme[:5]

array([1, 2, 3, 4, 5])

In [137]:
arrdeneme[:5]=10

In [138]:
arrdeneme

array([10, 10, 10, 10, 10])

In [143]:
arraydeneme1= np.arange(1,17)

In [144]:
arraydeneme1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [146]:
arraydeneme1.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [147]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [165]:
np.random.rand(0,6)

array([], shape=(0, 6), dtype=float64)

In [150]:
np.random.randint(0,6)

4

In [152]:
np.random.random(6)

array([0.44803329, 0.62582056, 0.97702702, 0.25793887, 0.15346839,
       0.68127996])

In [171]:
float(np.random.randint(0,5))

2.0

In [172]:
np.random(0,5)

TypeError: 'module' object is not callable

In [199]:
np.random.randn(36).reshape(6,6)

array([[ 0.62564468,  0.56766171, -0.50572058, -1.27528185, -0.02333089,
         0.89862702],
       [-0.79932065,  0.88476818, -0.84814062, -1.61843656,  1.23389368,
         2.04135939],
       [ 0.00885285, -0.96251814,  0.90764968,  0.9800611 ,  1.07597756,
         0.02634532],
       [ 0.46578865,  0.43788003, -1.21219435, -1.24907709,  0.88912797,
        -0.79807567],
       [ 0.07314654,  0.48753373, -0.51038032,  0.56023663,  0.07969976,
         1.50193689],
       [ 0.24086875, -1.44970058,  1.32583276,  0.784444  ,  0.53332484,
        -1.82267066]])

In [192]:
np.random.rand() * 5

1.8164186349204807

In [206]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [214]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [215]:
arr=np.arange(1,101)

In [216]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [220]:
newArray5=arr.reshape(10,10)

In [229]:
newArray5[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [230]:
newArray5[:6]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [231]:
newArray5[:5:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [234]:
newArray5[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [235]:
newArray5[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [236]:
newArray5[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])